# Generated by Django 5.0.4 on 2024-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0012_alter_process_data_alter_task_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
